### ISSUE TITLE
Just a question

### ISSUE THREAD

**Issue by cptmedic** [zjosua/Pokemanki#1]
If I switch from the other version of pokemanki will i lose my pokemon or will they be kept on your new version?

**Comment by zjosua** [comment]
If you use the release [v1.0.0](https://github.com/zjosua/Pokemanki/releases/tag/v1.0.0) or on AnkiWeb, you'll keep your Pokémon and settings.

The most recent commits in this repo (starting from acae1c9) currently don't read the old config and progress files, but I plan to add a legacy importer.

**Comment by zjosua** [comment]
The recently published version 1.1.1 has an importer for the legacy config and progress.
