### ISSUE TITLE
Error Report after downloading new Pokemanki Version for anki 2.1.54+

### ISSUE THREAD

**Issue by ahodapp11** [zjosua/Pokemanki#25]
#### Describe the bug
When I download the new pokemanki version from the code, I get an error message, and the pokemon do not show on stats page.

*If Anki shows an error message, copy and paste it between the backticks below.*
```Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue to the add-on author.
Debug info:
Anki 2.1.54 (b6a7760c) Python 3.9.7 Qt 5.14.1 PyQt 5.14.1
Platform: Mac 12.5.1
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2022-10-31 21:02:39
Add-ons possibly involved: ⁨Pokmanki⁩

Caught exception:
Traceback (most recent call last):
  File "aqt.progress", line 118, in handler
  File "aqt.main", line 197, in on_window_init
  File "aqt.main", line 290, in setupProfile
  File "aqt.main", line 470, in loadProfile
  File "aqt.hooks_gen", line 3244, in __call__
  File "/Users/andreahodapp/Library/Application Support/Anki2/addons21/1041307953/__init__.py", line 40, in startup
    from . import main
  File "/Users/andreahodapp/Library/Application Support/Anki2/addons21/1041307953/main.py", line 28, in <module>
    from .gui.pokemanki_options import invoke_pokemanki_options
  File "/Users/andreahodapp/Library/Application Support/Anki2/addons21/1041307953/gui/pokemanki_options.py", line 52, in <module>
    from .forms import pokemanki_options
  File "/Users/andreahodapp/Library/Application Support/Anki2/addons21/1041307953/gui/forms/__init__.py", line 23, in <module>
    from .qt5 import *  # noqa: F401
ModuleNotFoundError: No module named '1041307953.gui.forms.qt5'


```

#### To Reproduce
1. Download pokemanki from code 1041307953
2. Restart Anki

#### Expected behavior
*I expected to be able to see my pokemon and continue using pokemanki as I once did in the past. 

#### What have you tried?
I downloaded a pokemanki file from this website: https://github.com/zjosua/Pokemanki/releases

#### Screenshots
*If applicable, add screenshots to help explain your problem.*

#### Information about your set-up
*Open Anki, go to Help > About and click on "Copy Debug Info". Paste the result between the backticks below.*
```
    
    Anki 2.1.54 (b6a7760c) Python 3.9.7 Qt 5.14.1 PyQt 5.14.1
    Platform: Mac 12.5.1
    Flags: frz=True ao=True sv=2
    Add-ons, last update check: 2022-10-31 21:02:39
    
    
    ===Add-ons (active)===
    (add-on provided name [Add-on folder, installed at, version, is config changed])
    AMBOSS add-on ['0amboss_addon', 2022-09-08T08:45, 'None', mod]
    Colorful Tags  Hierarchical Tags ['594329229', 2022-09-15T11:06, 'None', '']
    Pokmanki ['1041307953', 2022-10-26T15:22, 'None', '']
    Special Fields ['1102281552', 2022-02-23T12:27, 'None', mod]
    
    ===IDs of active AnkiWeb add-ons===
    1041307953 1102281552 594329229
    
    ===Add-ons (inactive)===
    (add-on provided name [Add-on folder, installed at, version, is config changed])
    Pokémanki ['pokemanki', 2022-10-26T14:58, 'None', '']

```

What operating system are you using?
- OS: Monterey 12.5.1
- version:

**Comment by kimo-supremo** [comment]
I get the exact same thing

**Comment by zjosua** [comment]
As stated in #24, the Qt6 version of Anki is required for this add-on to work.

**Comment by ahodapp11** [comment]
I apologize for the duplicate post as I did not see #24, my bad. As advised I updated my anki to Qt6 and but am still receiving this error message when trying to view pokemon in stats. 

Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue to the add-on author.
Debug info:
Anki 2.1.54 (b6a7760c) Python 3.9.7 Qt 6.3.1 PyQt 6.3.1
Platform: Mac 12.5.1
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2022-11-02 07:46:46
Add-ons possibly involved: ⁨Pokmanki⁩

Caught exception:
Traceback (most recent call last):
  File "/Users/andreahodapp/Library/Application Support/Anki2/addons21/1041307953/main.py", line 151, in <lambda>
    statsDialog.form.web.loadFinished.connect(lambda _: _onStatsOpen(statsDialog))
  File "/Users/andreahodapp/Library/Application Support/Anki2/addons21/1041307953/main.py", line 145, in _onStatsOpen
    js = (addon_dir / "web.js").read_text()
  File "pathlib", line 1267, in read_text
  File "encodings.ascii", line 26, in decode
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 6: ordinal not in range(128)

**Comment by zjosua** [comment]
> UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 6: ordinal not in range(128)

This is also already being discussed in another issue (#27).

And in general please don't follow up with new issues in the discussion of unrelated issues.
