### ISSUE TITLE
Pokemanki Issue

### ISSUE THREAD

**Issue by DonkeyTeeth203** [zjosua/Pokemanki#29]
**I get an error message when I open the Anki app and nothing pops up! I attached the message below. Is it my anki version? Please help!**

#### Troubleshooting Checklist
*Replace the space between the parentheses with an x to mark the items as verified.*
- [x ] I have veryfied that my issue has not been reported yet in the [issue tracker](https://github.com/zjosua/Pokemanki/issues?q=is%3Aissue).
      *If you have an issue that has already been reported, join the discussion of the existing issue instead of creating a new one.*
- [x ] I am using the latest version of the add-on from AnkiWeb.
- [x ] My Anki installation meets the [compatibility requirements](https://github.com/zjosua/Pokemanki#compatibility).

#### Describe the bug
*A clear and concise description of what the bug is.*

*If Anki shows an error message, copy and paste it between the backticks below.*
Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue to the add-on author.
Debug info:
Anki 2.1.54 (b6a7760c) Python 3.9.7 Qt 5.15.2 PyQt 5.15.5
Platform: Windows 10
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2022-11-02 14:18:08

Caught exception:
Traceback (most recent call last):
  File "aqt.progress", line 118, in handler
  File "aqt.main", line 197, in on_window_init
  File "aqt.main", line 243, in setupProfileAfterWebviewsLoaded
  File "aqt.main", line 290, in setupProfile
  File "aqt.main", line 470, in loadProfile
  File "aqt.hooks_gen", line 3244, in __call__
  File "C:\Users\steve\AppData\Roaming\Anki2\addons21\1041307953\__init__.py", line 40, in startup
    from . import main
  File "C:\Users\steve\AppData\Roaming\Anki2\addons21\1041307953\main.py", line 28, in <module>
    from .gui.pokemanki_options import invoke_pokemanki_options
  File "C:\Users\steve\AppData\Roaming\Anki2\addons21\1041307953\gui\pokemanki_options.py", line 52, in <module>
    from .forms import pokemanki_options
  File "C:\Users\steve\AppData\Roaming\Anki2\addons21\1041307953\gui\forms\__init__.py", line 23, in <module>
    from .qt5 import *  # noqa: F401
ModuleNotFoundError: No module named '1041307953.gui.forms.qt5'

#### To Reproduce
1. Download
2. Open Anki

#### Expected behavior
I get this error message when I open Anki

#### What have you tried?
Nothing, unsure how to act

#### Screenshots
*If applicable, add screenshots to help explain your problem.*

#### Information about your set-up
*Open Anki, go to Help > About and click on "Copy Debug Info". Paste the result between the backticks below.*
```

```

What operating system are you using?
- OS: Windows 11
- version: 2.1.54

#### Additional context
*Add any other context about the problem here.*

**Comment by zjosua** [comment]
Yes, it is your Anki version. You need the Qt6 build, but you currently have the Qt5 build.

**Comment by DonkeyTeeth203** [comment]
Thank you, I will try to update it
