### ISSUE TITLE
Compatibility with both QT5 and QT6 versions of Anki (proposing possible solution)

### ISSUE THREAD

**Issue by EccentricConcentric** [zjosua/Pokemanki#31]
#### Troubleshooting Checklist
*Replace the space between the parentheses with an x to mark the items as verified.*
- [ ] I have verified that my issue has not been reported yet in the [issue tracker](https://github.com/zjosua/Pokemanki/issues?q=is%3Aissue).
      *If you have an issue that has already been reported, join the discussion of the existing issue instead of creating a new one.*

    This issue has been reported on the anki addon page as well as in closed report, #30 , however, I found a solution that should preserve current functionality with QT6 while expanding functionality to QT5 (which is the version I have).

- [X] I am using the latest version of the add-on from AnkiWeb.

- [ ] My Anki installation meets the [compatibility requirements](https://github.com/zjosua/Pokemanki#compatibility).
    While my installation is up-to-date, it is QT5, but I actually got it working on mine with some tinkering.

#### Describe the bug
*A clear and concise description of what the bug is.*

Add-on does not currently work in QT5, but seems to be solvable.

*If Anki shows an error message, copy and paste it between the backticks below.*
```python

```

#### To Reproduce
1. ..... Have latest Anki QT5 version installed
2. ..... Download Pokemanki add-on

#### Expected behavior
*A clear and concise description of what you expected to happen.*

Add-on working in QT5 similar to QT6

#### What have you tried?
*Before we suggest or explore something you've already discovered to not work, tell us what you have already tried to fix the problem.*

1) Within 1041307953\gui\pokemanki_trade.py , it attempts to import version sensitive files:

```python
from PyQt6 import QtCore, QtWidgets

from .forms.qt6 import pokemanki_trade
```

This can become QT5/QT6 agnostic by replacing the above with:

```python
try:
    from PyQt5 import QtCore, QtWidgets
except:
    from PyQt6 import QtCore, QtWidgets

from .forms.qt6 import pokemanki_trade
```

2) Then go to the folder 1041307953\gui\forms\ . Create a copy of the folder qt6 and rename it to qt5. There should now be 1041307953\gui\forms\qt6 and 1041307953\gui\forms\qt5 .

3) Within both 1041307953\gui\forms\qt5\pokemanki_options.py and 1041307953\gui\forms\qt5\pokemanki_trade.py replace:

```python
from PyQt6 import QtCore, QtGui, QtWidgets
```

with

```python
try:
    from PyQt5 import QtCore, QtGui, QtWidgets
except:
    from PyQt6 import QtCore, QtGui, QtWidgets
```

4) Do the same changes for the files in the qt6 folder: 1041307953\gui\forms\qt6\pokemanki_options.py and 1041307953\gui\forms\qt6\pokemanki_trade.py

Hope this helps, and hope the add-on can be updated soon for other QT5 users! Thanks for all your work.

#### Screenshots
*If applicable, add screenshots to help explain your problem.*
See screenshots below.

#### Information about your set-up
*Open Anki, go to Help > About and click on "Copy Debug Info". Paste the result between the backticks below.*
```
    
    Anki 2.1.54 (b6a7760c) Python 3.9.7 Qt 5.15.2 PyQt 5.15.5
    Platform: Windows 10
    Flags: frz=True ao=True sv=3
    Add-ons, last update check: 2022-11-19 13:45:50
    
    
    ===Add-ons (active)===
    (add-on provided name [Add-on folder, installed at, version, is config changed])
    AMBOSS add-on ['0amboss_addon', 2022-09-08T05:45, 'None', mod]
    Add Hyperlink ['318752047', 2022-05-23T06:16, 'None', '']
    Advanced Browser ['874215009', 2022-09-26T17:28, 'None', '']
    Ankimote - remote to control Anki from your phone ['149004221', 2021-08-11T09:57, 'None', '']
    BetterSearch ['1052724801', 2022-01-25T15:25, 'None', '']
    Browser TableEditor side-by-side horizontal split ['831846358', 2022-01-25T15:11, 'None', '']
    Extended Card Stats During Review ['1008566916', 2017-08-29T11:59, 'None', '']
    Extended Heatmap Updated January 2022 ['2011818092', 2022-02-01T19:28, 'None', '']
    Extended Tag AddEdit Dialog ['1135507717', 2022-03-13T03:41, 'None', '']
    Fastbar- with nightmode support ['46611790', 2022-04-14T20:04, 'None', '']
    Highlight Search Results in the Browser ['225180905', 2021-03-10T10:06, 'None', '']
    Hint Hotkeys ['1844908621', 2017-08-29T11:53, 'None', '']
    Learning Step and Review Interval Retention ['1949865265', 2022-08-28T13:21, 'None', '']
    More Decks Stats and Time Left ['1556734708', 2022-10-09T05:05, 'None', '']
    Pokmanki ['1041307953', 2022-11-03T09:52, 'None', '']
    Reset Ease ['947935257', 2020-12-27T07:59, 'None', '']
    Review Heatmap ['1771074083', 2022-07-23T00:34, 'None', '']
    Special Fields ['1102281552', 2022-02-23T10:27, 'None', '']
    Straight Reward ['957961234', 2022-03-31T12:37, 'None', '']
    The KING of Button Add-ons ['374005964', 2020-04-17T15:33, 'None', '']
    
    ===IDs of active AnkiWeb add-ons===
    1008566916 1041307953 1052724801 1102281552 1135507717 149004221 1556734708 1771074083 1844908621 1949865265 2011818092 225180905 318752047 374005964 46611790 831846358 874215009 947935257 957961234
    
    ===Add-ons (inactive)===
    (add-on provided name [Add-on folder, installed at, version, is config changed])
    Legacy ReMemorize ['323586997', 2020-11-19T22:27, 'None', '']
    Pokemanki ['633922407', 2021-02-24T11:49, 'None', '']
```

What operating system are you using?
- OS: Windows
- version: 10

#### Additional context
*Add any other context about the problem here.*
![2022-11-20 11_42_27-Clipboard](https://user-images.githubusercontent.com/6435037/202921574-671c9066-7fe8-4073-8150-6081770f060e.png)
![2022-11-20 11_42_59-Statistics](https://user-images.githubusercontent.com/6435037/202921576-3e933a3f-af2f-45fa-adbd-89b676276fe9.png)

**Comment by EccentricConcentric** [comment]
I found a better way to fix the issue:

1) Within 1041307953\gui\pokemanki_trade.py replace 
```python
from PyQt6 import QtCore, QtWidgets

from .forms.qt6 import pokemanki_trade
```
with
```python
from typing import TYPE_CHECKING

from aqt.qt import qtmajor

if TYPE_CHECKING or qtmajor >= 6:
    from PyQt6 import QtCore, QtWidgets
    from .forms.qt6 import pokemanki_trade  # noqa: F401
else:
    from PyQt5 import QtCore, QtWidgets
    from .forms.qt5 import pokemanki_trade  # noqa: F401
```

2) Create a copy of the folder 1041307953\gui\forms\qt6 and rename it to qt5, so that both qt5 and qt6 exist.

3) This time, the folder qt6 can be left unchanged. Within both 1041307953\gui\forms\qt5\pokemanki_options.py and 1041307953\gui\forms\qt5\pokemanki_trade.py replace
```python
from PyQt6 import QtCore, QtGui, QtWidgets
```
with
```python
from PyQt5 import QtCore, QtGui, QtWidgets
```

That should be enough to work, and does proper QT version checking, as opposed to using type/except.

**Comment by zjosua** [comment]
- Ffs, why can't people just update their PyQt?
- The contents of gui/forms are generated by aab. Manual changes to those files will be overwritten everytime the add-on is updated.
- aab can be configured to create the Qt5 compatible files in gui/forms/qt5.
- Some manually written Qt code might still be incompatible with Qt5.

And now, stubborn defenders of the deprecated and olden Qt5, bravely go forth and test the attached build with Anki's Qt5 build.
I removed a bunch of pokemon_images due to github's file size restriction. You might have to add them manually from your current installation.
[Pokemanki-v1.2.1-12-g78b3c1c-qt5+qt6.zip](https://github.com/zjosua/Pokemanki/files/10069195/Pokemanki-v1.2.1-12-g78b3c1c-qt5%2Bqt6.zip)

**Comment by EccentricConcentric** [comment]
Oh, I'd LOVE to update to QT6, if I weren't a med school student using a bunch of add-ons to make studying with Anki more efficient that were compatible with QT6. Waiting for the day where I can update with no loss of functionality.

So I just edited a few lines here and there to get this Pokemanki working for the dopamine hit to keep studying so I can continue the grind, and maybe help a few other med students who can't update to PyQT6 yet.

**Comment by zjosua** [comment]
So... will you help those poor souls by testing the package in my previous comment?

**Comment by zjosua** [comment]
@Aurichamp and @cptmedic are you still using Qt5? If so, it would be nice if you could test the build posted in the comment above.
I think it should work for Qt5, but I don't want to mess up my system just to test it.

**Comment by zjosua** [comment]
Ok, I tested it myself. Seems to work.

**Comment by kenzoitb** [comment]
> Ok, I tested it myself. Seems to work.
hi, i managed to capture a mewtwo in trade for my charizard, i traded it and restarted on ( i been using QT6 for ages) and everything reset to lvl 14 and doesn't level up at all. I need some help as it is making me a bit disappointed, first i got a trade for the best pokemon IMO and now its gone, now the pokemon all arent level 100 as they were, they are stuck at level 14 with a specific xp ( 8 bars till full) n consistently not leveling up AT ALL. this is seriously disappointing. can you fix this or help,  I've tried to reach you but you don't reply.
