### ISSUE TITLE
Pokemon Stats Window BOX  Sideways Request

### ISSUE THREAD

**Issue by kenzoitb** [zjosua/Pokemanki#37]
#### Is your feature request related to a problem? Please describe.
*A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]*
Please make an pokemon list sideways instead of scrolling downwards for stats window
#### Describe the solution you'd like
*A clear and concise description of what you want to happen.*
A square box containing my pokemon in a box 
#### Describe alternatives you've considered
*A clear and concise description of any alternative solutions or features you've considered.*
I tried looking at doing it but it was coding i don't want to mess up more
#### Additional context
*Add any other context or screenshots about the feature request here.*

**Comment by LordxRequiem** [comment]
Having the pokemon scroll downwards endlessly is a nonstarter for me using this add on, and I feel like displaying the pokemon sideways (as the original add on did) is an easy fix. Also it for some reason needs to recalculate my pokemon levels for minutes at a time every single time I open the stat page.

**Comment by LordxRequiem** [comment]
Doesn't work. "hscroll" string crashes application.
