### ISSUE TITLE
Configuration options for difficulty

### ISSUE THREAD

**Issue by Dazaisan99** [zjosua/Pokemanki#39]
#### Is your feature request related to a problem? Please describe.
I have just downloaded the addon, and there's just one thing that isn't satisfying me. I've been reviewing cards for the past ~ 7 months now, and the issue is that almost all my pokemon are lvl. 100 already.

#### Describe the solution you'd like
I'd like some kind of option to change the difficulty in the config, such as "1 card = n xp. points"

#### Describe alternatives you've considered
None (sorry)

#### Additional context
*Add any other context or screenshots about the feature request here.*
![image](https://user-images.githubusercontent.com/96884464/220307207-ca849c09-87d4-40dd-8975-eb1ba8cc05fe.png)
The first two pokemon, this is the same for almost all other decks. I just installed the addon.

**Comment by Fermino0314** [comment]
Same... hope it gets fixed soon

**Comment by zjosua** [comment]
This is a great idea.

I will probably not get around to work on it before September though, because I am preparing for final exams.
But if someone else would make a PR to implement this, I would support it.

**Comment by masonofa** [comment]
Not a perfect solution but have you tried the prestige menu? It drops the pokemon you select down 50 levels so you can grind their decks more.
