### ISSUE TITLE
Pokemanki doesn't work with newest release

### ISSUE THREAD

**Issue by metrast** [zjosua/Pokemanki#43]
#### Troubleshooting Checklist

- [x] I have veryfied that my issue has not been reported yet in the [issue tracker](https://github.com/zjosua/Pokemanki/issues?q=is%3Aissue).
      *If you have an issue that has already been reported, join the discussion of the existing issue instead of creating a new one.*
- [x] I am using the latest version of the add-on from AnkiWeb.
- [x] My Anki installation meets the [compatibility requirements](https://github.com/zjosua/Pokemanki#compatibility).

#### Describe the bug
The Pokemanki submenu doesn't show up under 'Tools'. The stats page doesn't show any Pokemon.

```python

```

#### To Reproduce
1. Install latest Version 1.3.5

#### Expected behavior
I expected Pokemanki to work like before the latest release.

#### What have you tried?
I tried disabling and re-enabling the add-on. With restarts of Anki in between.

#### Screenshots
-

#### Information about your set-up
```
    
    Anki 2.1.65 (aa9a734f) Python 3.9.15 Qt 6.5.0 PyQt 6.5.0
    Platform: macOS-13.5.1-x86_64-i386-64bit
    Flags: frz=True ao=True sv=3
    Add-ons, last update check: 2023-09-14 14:40:04
    
    
    ===Add-ons (active)===
    (add-on provided name [Add-on folder, installed at, version, is config changed])
    '' ['reviewer_progress_bar', 0, 'None', '']
    AMBOSS add-on ['0amboss_addon', 2022-06-27T18:14, 'None', '']
    AnkiHub ['1322529746', 2023-09-11T19:27, 'None', '']
    Colorful Tags  Hierarchical Tags ['594329229', 2022-09-15T17:06, 'None', '']
    Customize Keyboard Shortcuts ['24411424', 2022-09-14T11:12, 'None', mod]
    Edit Field During Review Cloze ['385888438', 2023-07-31T15:21, '6.15', mod]
    Exam Notifier ['236593452', 2023-01-19T18:12, 'None', '']
    High Yield Tags ['1918380616', 2023-01-10T20:14, 'None', '']
    Image Occlusion Enhanced for Anki 21 ['1374772155', 2022-04-09T09:15, 'None', '']
    Pokmanki ['1041307953', 2023-09-14T14:05, 'None', mod]
    Refocus Card when Reviewing 21 ['1642550423', 2018-09-19T16:14, 'None', '']
    Review Heatmap ['1771074083', 2022-06-30T03:43, 'None', '']
    Special Fields ['1102281552', 2022-11-22T02:49, 'None', mod]
    Symbols ['1461102936', 2019-04-18T22:21, 'None', mod]
    
    ===IDs of active AnkiWeb add-ons===
    1041307953 1102281552 1322529746 1374772155 1461102936 1642550423 1771074083 1918380616 236593452 24411424 385888438 594329229
    
    ===Add-ons (inactive)===
    (add-on provided name [Add-on folder, installed at, version, is config changed])
    Leaderboard ['41708974', 2023-01-15T11:53, 'None', mod]

```

What operating system are you using?
- OS: macOS
- version: Ventura 13.5.1

#### Additional context
-

**Comment by masonofa** [comment]
I am having this same issue. Add-on is not working at all now. Nothing shown in stats menu, add-on no longer has an option under the tools bar.

Debug info:
    
    Anki 2.1.65 (aa9a734f) Python 3.9.15 Qt 6.4.3 PyQt 6.4.0
    Platform: Windows-10-10.0.22621
    Flags: frz=True ao=True sv=3
    Add-ons, last update check: 2023-09-14 08:48:42
    
    
    ===Add-ons (active)===
    (add-on provided name [Add-on folder, installed at, version, is config changed])
    '' ['popup_dictionary', 0, 'None', mod]
    AMBOSS add-on ['0amboss_addon', 2023-07-24T05:20, 'None', mod]
    Add Hyperlink ['318752047', 2023-06-18T05:39, 'None', '']
    Additional Card Fields Fork for 21 ['744725736', 2022-10-23T04:10, 'None', mod]
    Advanced Browser ['874215009', 2023-07-01T13:55, 'None', '']
    Anki Simulator ['817108664', 2021-08-07T13:24, 'None', '']
    AnkiHub ['1322529746', 2023-09-11T11:27, 'None', '']
    Ankimote - remote to control Anki from your phone ['149004221', 2021-08-11T10:57, 'None', '']
    Batch Editing ['291119185', 2019-09-19T11:04, 'None', '']
    BetterSearch ['1052724801', 2023-06-15T14:44, 'None', mod]
    Clickable Tags v20 ['1739176371', 2022-01-30T15:58, 'None', '']
    Contanki - Controller Support for Anki beta ['1898790263', 2023-02-01T18:04, 'v0.9.2-beta', mod]
    Convert Subdecks to Tag Hierarchy ['1172858842', 2023-02-07T11:15, 'None', '']
    Custom Background Image and Gear Icon ['1210908941', 2023-04-18T19:19, 'None', mod]
    Customize Keyboard Shortcuts ['24411424', 2022-09-14T03:12, 'None', mod]
    Extended Card Stats During Review ['1008566916', 2017-08-29T12:59, 'None', '']
    Extended Tag AddEdit Dialog ['1135507717', 2023-06-04T13:24, 'None', mod]
    Fastbar- with nightmode support ['46611790', 2023-06-27T05:47, 'None', '']
    High Yield Tags ['1918380616', 2023-01-10T12:14, 'None', mod]
    Highlight Search Results in the Browser ['225180905', 2021-03-10T10:06, 'None', '']
    Hint Hotkeys ['1844908621', 2023-04-14T08:13, 'None', '']
    Image Editor ['307397307', 2022-09-07T22:09, 'None', '']
    Image Occlusion Enhanced ['1374772155', 2022-04-09T01:15, 'None', '']
    Image Style Editor ['1593969147', 2021-12-17T00:01, 'None', mod]
    ImageResizer ['1214357311', 2022-07-15T07:05, 'None', '']
    Leaderboard ['41708974', 2023-01-15T03:53, 'None', mod]
    Learning Step and Review Interval Retention ['1949865265', 2022-08-28T14:21, 'None', '']
    More Decks Stats and Time Left ['1556734708', 2023-08-21T05:27, 'None', mod]
    More Overview Stats 21 ['738807903', 2021-07-30T13:13, 'None', mod]
    Placeholder- KoST ['907028815', 2022-03-04T09:59, 'None', '']
    Pokmanki ['1041307953', 2023-09-14T06:05, 'None', mod]
    Quick Colour Changing ['2491935955', 2022-07-23T22:29, 'None', mod]
    Rebuild All  Empty All for Anki 21 ['1810938259', 2018-07-19T22:40, 'None', '']
    Reset Ease ['947935257', 2020-12-27T07:59, 'None', '']
    Review Heatmap ['1771074083', 2022-06-29T19:43, 'None', '']
    Special Fields ['1102281552', 2022-11-21T18:49, 'None', mod]
    Speed Focus Mode auto-alert auto-reveal auto-answer ['1046608507', 2022-12-16T04:24, 'None', mod]
    Straight Reward ['957961234', 2022-12-12T06:49, 'None', '']
    Symbols As You Type ['2040501954', 2022-06-07T22:09, 'None', '']
    Symbols ['1461102936', 2019-04-23T07:37, 'None', mod]
    The KING of Button Add-ons ['374005964', 2023-02-17T16:21, 'None', mod]
    True Retention ['613684242', 2017-11-19T13:43, 'None', '']
    Web Browser - Search terms Import texts and images automatically ['864545277', 2022-08-02T14:49, 'None', mod]
    add-on dialog searchfilter bar ['561945101', 2023-06-15T06:39, 'None', '']
    when is next learning card due today due ['563204849', 2021-12-06T08:06, 'None', mod]
    
    ===IDs of active AnkiWeb add-ons===
    1008566916 1041307953 1046608507 1052724801 1102281552 1135507717 1172858842 1210908941 1214357311 1322529746 1374772155 1461102936 149004221 1556734708 1593969147 1739176371 1771074083 1810938259 1844908621 1898790263 1918380616 1949865265 2040501954 225180905 24411424 2491935955 291119185 307397307 318752047 374005964 41708974 46611790 561945101 563204849 613684242 738807903 744725736 817108664 864545277 874215009 907028815 947935257 957961234
    
    ===Add-ons (inactive)===
    (add-on provided name [Add-on folder, installed at, version, is config changed])
    '' ['put_ALL_due_learning_cards_first', 0, 'None', '']
    Anki Zoom ['538879081', 2020-04-03T18:20, 'v1.1.3', '']
    Collapsible Fields ['1896168623', 2021-08-28T15:45, 'None', '']
    Exam Notifier ['236593452', 2023-01-19T10:12, 'None', '']
    Load Balanced Scheduler ['208879074', 2019-07-23T20:37, 'None', '']
    Mini Format Pack ['295889520', 2019-03-01T20:13, 'None', '']
    Puppy Reinforcement ['puppy_reinforcement', 2020-02-05T00:16, 'None', '']
    Stats Plus ['1009670238', 2021-03-04T05:23, 'None', '']
    Syllabus - Anki Statistics and Export by Tag and Deck ['668156440', 2020-01-19T12:52, 'None', mod]
    Wrapper meta-addon ['396502676', 2023-07-22T06:05, 'None', '']

**Comment by Zeroman123456** [comment]
I confirm

**Comment by mohitnysa** [comment]
The error can be fixed by uninstalling the addon and reinstalling it via the direct download here:
https://github.com/zjosua/Pokemanki/releases/download/v1.3.5/Pokemanki-v1.3.5-qt5+qt6.ankiaddon

not sure why updating within anki doesn't work..

**Comment by metrast** [comment]
If you download via Ankiweb there are some weird configuration options in the config menu. It looks like it's for a different add-on.

**Comment by moniquemurphy** [comment]
I did a little debugging today. Upon opening the Stats page...

In `compute.py`, `deckmon = msgbox.clickedButton().text()` is None, and throws an error. Working backwards, it looks like after the "Choose a deck for your starter Pokemon" dialog pops up, the "Choose a starter Pokemon for [deck name]" dialog never appears. I tested with some `QMessageBox()` options both before and after the that dialog like so (around line 230)

```
msgbox = QMessageBox()
    msgbox.setText("I'm testing some stuff part 1")
    msgbox.exec()
    
window = QWidget()
inp, ok = QInputDialog().getItem(
    window,
    "Pokémanki",
    "Choose a deck for your starter Pokémon",
    decklist,
    0,
    False,
)
    
 msgbox = QMessageBox()
 msgbox.setText("I'm testing some stuff part 2")
 msgbox.exec_()
```

First message box shows propertly, second one flashes briefly and then disappears. The deckmon message box is flashing and then disappearing. Not sure why `QInputDialog()` is interrupting any following `QMessageBox()`es.

**Comment by zjosua** [comment]
The packaged addon from ankiweb had only like half the files in it.
Maybe I uploaded the one for local distribution and the ankiweb server did some weird stuff to it.

Anyway, it should be working again. Feel free to reopen the issue if the same problem persists.

**Comment by reaganmil** [comment]
I see this issue was closed, but I'm still having this problem. After adding it (I tried both downloading it and going through ankiweb) I close anki and restart so the add on is activated but I just get an error message
