### ISSUE TITLE
Is there some way we can get in touch so I can contribute here?

### ISSUE THREAD

**Issue by Exkywor** [zjosua/Pokemanki#6]
Hi, I love this addon and I'm hoping to contribute to it since there are things I would like to improve, like what I did by making the stats view responsive, and bugs I want to help fix.
However, rather than hoping for my code to get merged to the old repo or to do an effort alone on my fork, I was thining on starting to contribute here directly. I think you're doing great things with the code so far and I want to help and hopefully be able to implement some new things too.
So, I was wondering if there's any way we can get in contact, so I can run some ideas through you in case there are better ways to do them or you would like them to be done in a different way or not at all or things like that, before doing any PRs.
I've send you a DM on Discord in case you want to talk and want to do it through there.

P.D. Sorry about posting this here, but I couldn't find another way to contact you

Kind regards,
Exkywor

**Comment by zjosua** [comment]
Sure, let's coordinate on Discord.
If anyone else wants to chime in, ping us on the [Anki Discord channel](https://discord.gg/tTtAAgw7) or PM us on Discord.
